version: "3"

services:
  db:
    container_name: postgresql_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pg-admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "8080:8080"
    command: npm start
    depends_on: 
      - db

volumes:
  postgres-data: