version: "3.8"

services:
  db:
    container_name: postgresql_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pg-admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  node:
    container_name: node_server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "8080:8080"
    command: npm start
    environment:
      PORT: 8080
      NODE_ENV: development
    depends_on: 
      - db
      - pg-admin
    volumes:
      - D:\Kỳ 7\Hệ thống thông tin địa lí 3 chiều\Project\EtihadStadium-BE:/usr/src

volumes:
  postgres-data:
  pgadmin-data: